// <auto-generated />
using FinalProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20200518225240_UserMigration")]
    partial class UserMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("FinalProject.Entities.Group", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgeRestricted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("RightName")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("RightName");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("FinalProject.Entities.Right", b =>
                {
                    b.Property<string>("RightName")
                        .HasColumnType("TEXT");

                    b.HasKey("RightName");

                    b.ToTable("Right");
                });

            modelBuilder.Entity("FinalProject.Entities.User", b =>
                {
                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("groupName")
                        .HasColumnType("TEXT");

                    b.HasKey("LastName");

                    b.HasIndex("groupName");

                    b.ToTable("utilizatori");
                });

            modelBuilder.Entity("FinalProject.Entities.Group", b =>
                {
                    b.HasOne("FinalProject.Entities.Right", "right")
                        .WithMany()
                        .HasForeignKey("RightName");
                });

            modelBuilder.Entity("FinalProject.Entities.User", b =>
                {
                    b.HasOne("FinalProject.Entities.Group", "group")
                        .WithMany()
                        .HasForeignKey("groupName");
                });
#pragma warning restore 612, 618
        }
    }
}
